version: '2'

services:
  web:
    image: alexcheng/magento
    ports:
      - "80:80"
    links:
      - mysql
    env_file:
      - env
    depends_on: 
      - mysql
  mysql:
    image: mysql:5.6.23
    env_file:
      - env
