version: '2'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - /var/www/magento/app/etc:/var/www/magento/app/etc
      - /var/www/magento/skin:/var/www/magento/skin
      - /var/www/magento/var:/var/www/magento/var
    links:
      - mysql
    env_file:
      - env
    depends_on: 
      - mysql
  mysql:
    image: mysql:5.6.23
    env_file:
      - env
